// <auto-generated />
using System;
using MRLserver.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MRLserver.Migrations
{
    [DbContext(typeof(MRLserverContext))]
    [Migration("20241113144337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MRLserver.Models.MRLclass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("UID")
                        .HasColumnType("int");

                    b.Property<string>("karbantarto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("kovetkezoKarbantartas")
                        .HasColumnType("datetime2");

                    b.Property<string>("telepitesHelye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("telepitesIdeje")
                        .HasColumnType("datetime2");

                    b.Property<string>("telepitesPozicioja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telepitestVegezte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("utolsoKapcsolataLifttel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("utolsoKarbantartasIdeje")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("MRLclass");
                });
#pragma warning restore 612, 618
        }
    }
}
